services:
  - type: web
    name: moyd-listmonk
    env: docker
    dockerfilePath: ./listmonk-deployment/Dockerfile
    region: oregon
    plan: starter

    healthCheckPath: /api/health

    envVars:
      - key: LISTMONK_ADMIN_USERNAME
        value: admin
      - key: LISTMONK_ADMIN_PASSWORD
        value: fucktrump67
      - key: LISTMONK_ROOT_URL
        value: https://mail.moyd.app/
      - key: DB_HOST
        value: aws-0-us-east-1.pooler.supabase.com
      - key: DB_PORT
        value: 6543
      - key: DB_USER
        value: postgres.faajpcarasilbfndzkmd
      - key: DB_PASSWORD
        value: duFrit-7pyspe-kefryz
      - key: DB_NAME
        value: postgres
      - key: DB_SSL_MODE
        value: require
      - key: DB_SCHEMA
        value: listmonk
      - key: DB_PARAMS
        value: search_path=listmonk&statement_cache_mode=disable
